-- 1. Tabla para almacenar la cabecera de los resúmenes diarios
CREATE TABLE public.resumenes_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    fecha_resumen DATE NOT NULL,
    numero_completo TEXT NOT NULL,
    correlativo TEXT NOT NULL,
    ticket TEXT NOT NULL,
    estado_sunat TEXT,
    summary_api_id BIGINT UNIQUE -- ID del resumen en el sistema de facturación
);

COMMENT ON TABLE public.resumenes_diarios IS 'Almacena la información de cabecera de los resúmenes diarios enviados a SUNAT.';
COMMENT ON COLUMN public.resumenes_diarios.ticket IS 'Ticket de seguimiento proporcionado por SUNAT.';

-- 2. Tabla para almacenar el detalle de boletas por cada resumen
CREATE TABLE public.resumen_diario_boletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resumen_id BIGINT NOT NULL REFERENCES public.resumenes_diarios(id) ON DELETE CASCADE,
    serie_numero TEXT NOT NULL
);

COMMENT ON TABLE public.resumen_diario_boletas IS 'Almacena las boletas individuales incluidas en cada resumen diario.';

-- 3. Habilitar Row Level Security (RLS)
ALTER TABLE public.resumenes_diarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resumen_diario_boletas ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de acceso (permitir a usuarios autenticados leer y escribir)
-- Ajuste los roles ('authenticated') según sus necesidades de seguridad.
CREATE POLICY "Allow all access to authenticated users"
ON public.resumenes_diarios
FOR ALL
TO authenticated
USING (TRUE)
WITH CHECK (TRUE);

CREATE POLICY "Allow all access to authenticated users"
ON public.resumen_diario_boletas
FOR ALL
TO authenticated
USING (TRUE)
WITH CHECK (TRUE);
